### ISSUE TITLE
Mac版本的有计划吗？

### ISSUE THREAD

**Issue by Bruce8580** [LokerL/loker-page#1]
感谢大佬 实力真的强 能否开发一个Mac版本的 或者网页版的？

**Comment by LokerL** [comment]
你好 ，感谢支持。

> 能否开发一个Mac版本的或者网页版的

因为没有MAC环境，测试的话很不方便，大概率不会支持MAC。
网页版的话可以使用一款油猴插件，功能类似：[Azure Speech Download](https://greasyfork.org/zh-CN/scripts/444347-azure-speech-download)
