### ISSUE TITLE
SSML时间过长的问题

### ISSUE THREAD

**Issue by Bruce8580** [LokerL/loker-page#2]
停在第3次上报...是你的文本里面有无法解析的内容。PS：现在已知无法解析的内容包括&和 SSML 以外的标签语言。

时间过长的话，是否可以加上报错或者停止按钮？不然只能关闭软件。
另外SSML的内容如果单独一行行的输入的话，可以成功转换成语音，几十行放到一起的话，就停在了第三次上报，是否是因为没有解除1000的限制？

**Comment by LokerL** [comment]
> 时间过长的话，是否可以加上报错或者停止按钮？不然只能关闭软件。

最近忙着工作的事情，一直没有更新。但是这个功能在计划列表里，并且正在开发中。


> 另外SSML的内容如果单独一行行的输入的话，可以成功转换成语音，几十行放到一起的话，就停在了第三次上报，是否是因为没有解除1000的限制？

SSML没有对文本切片，因为切片的的方式不太好控制。所以字数限制还是的400多字1k字符左右（接口默认限制）。

**Comment by Bruce8580** [comment]
感谢大佬百忙中抽空耐心解答。针对SSML的切片问题，我有一个不成熟的建议，你看是否从代码开发的角度来说易于实现。
就是直接用</voice>语法来切片，因为每一句都是以此结尾。

1. 这样的操作应该能够解决90%的用SSML的人群。
2. 因为如果是单一角色和音质的话，直接用text功能就好了。
3. 用SSML通常用来实现多人物角色对话，单个句子不会超过1000的限制；超过就迎来用Text来实现就好了。
4. 虽然不能覆盖100%的需求，但是应该能决绝大部分的需求，切片应该和你目前的text方法判定条件还要少。

   还请考虑是否能采纳这个建议。感谢。

**Comment by LokerL** [comment]
可以加入开发计划中。

**Comment by Bruce8580** [comment]
感谢答复。
